/* tslint:disable */
/* eslint-disable */
import { AgencyInfo } from '../models/agency-info';
import { FormOfPayment } from '../models/form-of-payment';
import { OriginalIssue } from '../models/original-issue';
import { PersonName } from '../models/person-name';
import { PreviousIssue } from '../models/previous-issue';
import { PricingTypeEnum } from '../models/pricing-type-enum';
import { SupplierLocator } from '../models/supplier-locator';
import { TicketId } from '../models/ticket-id';
import { TicketPrice } from '../models/ticket-price';
import { TicketSegment } from '../models/ticket-segment';
export type Ticket = TicketId & {

/**
 * The total number of tickets issued for the collection of flight segments example: 5
 */
'numberOfTicketsIssued': number;

/**
 * Electronic Settlement Authorization Code - A unique number generated by a Carrier to authorize or approve a transaction
 */
'settlementAuthorizationCode'?: string;

/**
 * A Tour Code on a flight ticket is a special code arranged between the Travel Agency and the Airlines
 */
'tourCode'?: string;

/**
 * The Account Code used to classify financial activities
 */
'accountCode'?: string;

/**
 * A code on airline tickets to indicate what type of discount is applied
 */
'ticketDesignator'?: string;
'PersonName': PersonName;
'ReservationLocator'?: SupplierLocator;
'FormOfPayment': Array<FormOfPayment>;
'TicketSegment': Array<TicketSegment>;
'TicketPrice': TicketPrice;

/**
 * Code used to identify Passengers according to various
 */
'PassengerTypeCode'?: string;

/**
 * The plating carrier of the ticket
 */
'ValidatingCarrier'?: string;
'PricingType'?: PricingTypeEnum;

/**
 * restrictions associated with a particular fare
 */
'Restrictions'?: Array<string>;
'AgencyInfo'?: AgencyInfo;
'OriginalIssue'?: OriginalIssue;
'PreviousIssue'?: Array<PreviousIssue>;
} & {
'@type'?: string;
};
